apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: node-hello
  name: node-hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.1
          image: trumanz/nodejs-hello
          name: node-hello
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
